name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
        project_id: ${{ secrets.GCLOUD_PROJECT }}
        export_default_credentials: true

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_SERVICE }} .
        docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_SERVICE }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.GCLOUD_SERVICE }} \
          --image gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_SERVICE }} \
          --region ${{ secrets.GCLOUD_REGION }} \
          --platform managed \
          --allow-unauthenticated
